baseURL = "https://bb.9ba.in/"
languageCode = "zh-cn"
title = "bb.9ba.in"
theme = "PaperMod"

[pagination]
  pagerSize = 10

enableRobotsTXT = true

[params]
  env = "production"
  description = "bb.9ba.in åšå®¢"
  author = "Victor"

  defaultTheme = "auto"   # auto / dark / light
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  disableSpecial1stPost = true
  comments = false

  [params.homeInfoParams]
    Title = "ğŸ‘‹ Hi"
    Content = "æ¬¢è¿æ¥åˆ° bb.9ba.in"

[menu]
  [[menu.main]]
    name = "æ–‡ç« "
    url = "/posts/"
    weight = 1

